# Generated by Django 5.1.7 on 2025-03-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('bezahlt', 'Bezahlt'), ('offen', 'Offen'), ('fehlgeschlagen', 'Fehlgeschlagen')], max_length=20)),
                ('zahlungsart', models.CharField(choices=[('Banküberweisung', 'Banküberweisung'), ('Kreditkarte', 'Kreditkarte'), ('PayPal', 'PayPal'), ('Lastschrift', 'Lastschrift')], max_length=20)),
                ('mietvertrag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_contracts.rentalcontract')),
            ],
        ),
    ]
