# Generated by Django 5.1.7 on 2025-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=100)),
                ('nachname', models.CharField(max_length=100)),
                ('geburtsdatum', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefonnummer', models.CharField(max_length=50)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('stadt', models.CharField(max_length=100)),
            ],
        ),
    ]
