# Generated by Django 5.1.7 on 2025-03-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rental_units', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertragsbeginn', models.DateField()),
                ('vertragsende', models.DateField()),
                ('mietzins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kaution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('aktiv', 'Aktiv'), ('beendet', 'Beendet')], max_length=20)),
                ('mieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('mietobjekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_units.rentalunit')),
            ],
        ),
    ]
