# Generated by Django 5.1.7 on 2025-03-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_payment'),
        ('rental_contracts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalContract',
        ),
    ]
