# Generated by Django 5.1.7 on 2025-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strasse', models.CharField(max_length=100)),
                ('hausnummer', models.CharField(max_length=10)),
                ('plz', models.CharField(max_length=10)),
                ('stadt', models.CharField(max_length=100)),
                ('baujahr', models.IntegerField()),
                ('anzahl_wohnungen', models.IntegerField()),
                ('anzahl_parkplaetze', models.IntegerField()),
                ('besitzer', models.CharField(max_length=255)),
            ],
        ),
    ]
