# Generated by Django 5.1.7 on 2025-03-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('rental_units', '0002_delete_rentalunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
