# Generated by Django 5.1.7 on 2025-03-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('Wohnung', 'Wohnung'), ('Büro', 'Büro'), ('Laden', 'Laden'), ('Penthouse', 'Penthouse')], max_length=20)),
                ('flaeche_m2', models.IntegerField()),
                ('zimmeranzahl', models.IntegerField()),
                ('miete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verfuegbar_ab', models.DateField()),
                ('status', models.CharField(choices=[('vermietet', 'Vermietet'), ('frei', 'Frei')], max_length=20)),
                ('ausstattungen', models.ManyToManyField(blank=True, to='features.feature')),
                ('liegenschaft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
                ('mieter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
        ),
    ]
